config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
 :registrations => 'users/registrations',
 :sessions => 'users/sessions'
}
  root to: 'items#index'
  resources :items, only: [:new, :create, :show, :edit, :update, :destroy, :buy] do
    resources :buyers, only: [:index] do
      collection do
        get 'done', to: 'buyers#done'
        post 'pay', to: 'buyers#pay'
      end
    end
    resources :item_images, only: [:create, :destroy]
    member do
      get 'buy'
    end
    collection do
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
    end
  end
  resources :users, only: [:show, :edit, :update, :logout] do
    resources :profiles, only: [:new, :create] do
      collection do
        get 'show', to: 'profiles#show'
      end
    end
    resources :delivery_destinations, only: [:new, :create] do
      collection do
        get 'edit', to: 'delivery_destinations#edit'
        patch 'update', to: 'delivery_destinations#update'
      end
    end
    member do
      get 'logout'
      get 'credit'
    end
  end
  resources :credit_cards, only: [:new, :show, :destroy] do
    collection do
      post 'pay', to: 'credit_cards#pay'
    end
  end

  resources :categories, only: [:index, :show]
end

app/models/delivery_destination.rb
class DeliveryDestination < ApplicationRecord
  belongs_to :user, optional: true
 
    validates :destination_family_name, presence: true
    validates :destination_first_name, presence: true
    validates :destination_family_name_kana, presence: true
    validates :destination_first_name_kana, presence: true
    validates :postal_code, presence: true
    validates :prefecture, presence: true
    validates :city, presence: true
    validates :house_number, presence: true

  # with_options presence: true do
  #   validates :destination_family_name
  #   validates :destination_first_name
  #   validates :destination_family_name_kana
  #   validates :destination_first_name_kana
  #   # validates :postal_code, format: {with: /\A\d{3}[-]\d{4}\z/}
  #   validates :prefecture
  #   validates :city
  #   validates :house_number
  # end

end

app/controllers/delivery_destinations_controller.rb
class DeliveryDestinationsController < ApplicationController

  def new
  end

  def create
  end

  def edit
    @delivery = DeliveryDestination.find(params[:user_id])
  end

  def update
    delivery = DeliveryDestination.find(params[:user_id])
    delivery.update(delivery_params)
    redirect_to user_path(current_user)
  end

  private
  def delivery_params
    params.require(:delivery_destination).permit(:destination_family_name, :destination_first_name, :destination_family_name_kana, :destination_first_name_kana, :postal_code, :prefecture, :city, :house_number, :building_name, :phone_number)
  end
  
end

app/helpers/delivery_destinations_helper.rb
module DeliveryDestinationsHelper
end

app/views/delivery_destinations/edit.html.haml
.wrapper
  = render 'users/mypage-side'
  .mypage-main
    %h2.mypage-main__head
      登録住所変更
    .mypage-main__container
      .content
        = form_for @delivery, url: user_delivery_destinations_path do |f|
          .form-group
            = f.label :name, '送付先お名前(全角)'
            %span.esessential-icon 必須
            %br
            = f.text_field :destination_family_name, placeholder: '山田', class:'destination_family_name'
            = f.text_field :destination_first_name, placeholder: '太郎', class:'destination_first_name'
          .form-group
            = f.label :kana, '送付先お名前カナ(全角)', class:'input-label' 
            %span.esessential-icon 必須    
            %br
            = f.text_field :destination_family_name_kana, placeholder: 'ヤマダ', class:'destination_family_name_kana'
            = f.text_field :destination_first_name_kana, placeholder: 'タロウ', class:'destination_first_name_kana'
          .form-group
            = f.label :postal_code, '郵便番号', class: 'input-label'
            %span.esessential-icon 必須 
            %br
            = f.text_field :postal_code, placeholder: '郵便番号 例：000-0000', class: 'postal_code'
          .form-group
            = f.label :prefecture, '都道府県', class: 'input-label'
            %span.esessential-icon 必須 
            %br
            = f.text_field :prefecture, placeholder: '都道府県 例：東京都', class: 'prefecture'
          .form-group
            = f.label :city, '市区町村', class: 'input-label'
            %span.esessential-icon 必須 
            %br
            = f.text_field :city, placeholder: '市区町村', class: 'city'
          .form-group
            = f.label :house_number, '番地', class: 'input-label'
            %span.esessential-icon 必須 
            %br
            = f.text_field :house_number, placeholder: '番地', class: 'house_number'
          .form-group
            = f.label :building_name, 'マンションやビル名、部屋番号', class: 'input-label'
            %span.optional-icon 任意
            %br
            = f.text_field :building_name, placeholder: 'マンションやビル名、部屋番号', class: 'building_name'
          .form-group
            = f.label :phone_number, '電話番号', class: 'input-label'
            %span.optional-icon 任意
            %br
            = f.text_field :phone_number, placeholder: '電話番号', class: 'phone_number'
            %br
          = f.submit "変更する", class: "submit"

app/views/delivery_destinations/new.html.haml
-# ユーザーの送付先情報ページです