config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
 :registrations => 'users/registrations',
 :sessions => 'users/sessions'
}
  root to: 'items#index'
  resources :items, only: [:new, :create, :show, :edit, :update, :destroy, :buy] do
    resources :buyers, only: [:index] do
      collection do
        get 'done', to: 'buyers#done'
        post 'pay', to: 'buyers#pay'
      end
    end
    resources :item_images, only: [:create, :destroy]
    member do
      get 'buy'
    end
    collection do
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
    end
  end
  resources :users, only: [:show, :edit, :update, :logout] do
    resources :profiles, only: [:new, :create] do
      collection do
        get 'show', to: 'profiles#show'
      end
    end
    resources :delivery_destinations, only: [:new, :create] do
      collection do
        get 'edit', to: 'delivery_destinations#edit'
        patch 'update', to: 'delivery_destinations#update'
      end
    end
    member do
      get 'logout'
      get 'credit'
    end
  end
  resources :credit_cards, only: [:new, :show, :destroy] do
    collection do
      post 'pay', to: 'credit_cards#pay'
    end
  end

  resources :categories, only: [:index, :show]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile, dependent: :destroy
  accepts_nested_attributes_for :profile
  has_one :credit_card, dependent: :destroy
  has_one :delivery_destination, dependent: :destroy
  accepts_nested_attributes_for :delivery_destination
  has_many :comments, dependent: :destroy
  has_many :buyer_items, foreign_key: "buyer_id", class_name: 'Items'
  has_many :seller_items, foreign_key: "seller_id", class_name: 'Items'
  

    validates :nickname, presence: true
    validates :email, presence: true
    validates :email, uniqueness: true
    validates :password, length: {minimum: 7}


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  
  def new
    @user = User.new
    # @user.profile.new
    # @profile = @user.profile.new
    # @profile = Profile.new
    @user.build_profile
    @user.build_delivery_destination
    # @user.delivery_destination.new
    # @delivery_destination = DeliveryDestination.new
  end

  def create

    @user = User.new(user_params)
    @user.profile.birth_day = params[:birth_day]["birth_day(1i)"]+ "-" + params[:birth_day]["birth_day(2i)"] + "-" + params[:birth_day]["birth_day(3i)"]
    if @user.save
    sign_in @user
    redirect_to root_path
    end
    # @profile = Profile.new(profile_params)
    # @user.build_profile

    # @delivery_destination = DeliveryDestination.new(delivery_destination_params)
    # @user.build_delivery_destination
  end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  private

   def user_params
    params.require(:user).permit(:nickname, :email, :password, profile_attributes: [:family_name, :first_name, :family_name_kana, :first_name_kana, :birth_day], delivery_destination_attributes: [:destination_family_name, :destination_first_name, :destination_family_name_kana, :destination_first_name_kana, :postal_code, :prefecture, :city, :house_number, :building_name, :phone_number])
   end
   
  #  def profile_params
  #   params.require(:profile).permit(:family_name, :first_name, :family_name_kana, :first_name_kana, :birth_year, :birth_month, :birth_day)
  #  end

  #  def delivery_destination_params
  #   params.require(:delivery_destination).permit(:destination_family_name, :destination_first_name, :destination_family_name_kana, :destination_first_name_kana, :postalcode, :prefectures, :city, :house_number, :building_name, :phone_number)
  #  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
    # ↓の seller_id:, buyer_id: は仮に"1"としている 実際はログインしているユーザーのidを入れたい
    @sell_items = Item.where(seller_id: current_user.id).order("created_at DESC").limit(3)
    @buyed_items = Item.where(buyer_id: current_user.id).order("created_at DESC").limit(3)
  end

  def edit
    card = CreditCard.find_by(user_id: current_user.id)
    if card.blank?
      redirect_to new_card_path 
    else
      Payjp.api_key = Rails.application.secrets[:PAYJP_PRIVATE_KEY]
      customer = Payjp::Customer.retrieve(card.costomer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  def update
  end

  def logout
  end

  def credit
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_logout.html.haml
.wrapper__main
  = link_to destroy_user_session_path, method: :delete do
    %button.logout ログアウト

app/views/users/_mypage-side.html.haml
.wrapper__side
  %ul
    = link_to user_path(current_user.id) do
      %li.wrapper__side__menu.wrapper__side__mypage
        %p マイページ
        = icon('fas', 'angle-right', class: 'wrapper__side__menu__icon wrapper__side__mypage__icon')
    = link_to user_profiles_path(current_user.id) do
      %li.wrapper__side__menu
        %p 本人情報
        = icon('fas', 'angle-right', class: 'wrapper__side__menu__icon')
    = link_to edit_user_delivery_destinations_path(current_user.id) do
      %li.wrapper__side__menu
        %p 登録住所編集
        = icon('fas', 'angle-right', class: 'wrapper__side__menu__icon')
    = link_to new_credit_card_path do
      %li.wrapper__side__menu
        %p クレジットカード情報
        = icon('fas', 'angle-right', class: 'wrapper__side__menu__icon')
    = link_to logout_user_path(current_user.id) do
      %li.wrapper__side__menu
        %p ログアウト
        = icon('fas', 'angle-right', class: 'wrapper__side__menu__icon')

app/views/users/_mypage-top.html.haml
.wrapper__main
  .wrapper__main__profile
    .wrapper__main__profile__user
      = link_to '#' do
        = image_tag 'mypage-icon.png', class: "wrapper__main__profile__user__icon"
        %p.wrapper__main__profile__user__name 
          = @user.nickname
  .wrapper__main__tabs
    %input#tab1{:name => 'tab-radio', :type => "radio", :checked => "checked"}
    %label.wrapper__main__tabs__left.tab(for="tab1")
      出品中の商品
    %input#tab2{:name => 'tab-radio', :type => "radio"}
    %label.wrapper__main__tabs__right.tab(for="tab2")
      購入した商品
    .wrapper__main__tabs__items#sell-items
      - @sell_items.each do |item|
        = link_to item_path(item.id) do
          .wrapper__main__tabs__items__item
            - item.item_images.each do |image|
              = image_tag image.image, class: 'wrapper__main__tabs__items__item__img'
              - break
            %p.wrapper__main__tabs__items__item__name
              = item.name
            %p.wrapper__main__tabs__items__item__price
              = item.price
              円 (税込)
    .wrapper__main__tabs__items#buyed-items
      - @buyed_items.each do |item|
        = link_to item_path(item.id) do
          .wrapper__main__tabs__items__item
            - item.item_images.each do |image|
              = image_tag image.image, class: 'wrapper__main__tabs__items__item__img'
              - break
            %p.wrapper__main__tabs__items__item__name
              = item.name
            %p.wrapper__main__tabs__items__item__price
              = item.price
              円 (税込)

app/views/users/_profile.html.haml
.wrapper__main
  .wrapper__main__profile
    .wrapper__main__profile__user
      = link_to '#' do
        = image_tag '/assets/mypage-icon.png', class: "wrapper__main__profile__user__icon"
        %p.wrapper__main__profile__user__name 
          = @user.nickname
  .wrapper__main__tabs
    %input#tab1{:name => 'tab-radio', :type => "radio", :checked => "checked"}
    %label.wrapper__main__tabs__left.tab(for="tab1")
      出品中の商品
    %input#tab2{:name => 'tab-radio', :type => "radio"}
    %label.wrapper__main__tabs__right.tab(for="tab2")
      購入した商品
    .wrapper__main__tabs__items#sell-items
      - @sell_items.each do |item|
        .wrapper__main__tabs__items__item
          - item.item_images.each do |image|
            = image_tag image.image, class: 'wrapper__main__tabs__items__item__img'
            - break
          %p.wrapper__main__tabs__items__item__name
            = item.name
          %p.wrapper__main__tabs__items__item__price
            = item.price
            円 (税込)
    .wrapper__main__tabs__items#buyed-items
      - @buyed_items.each do |item|
        .wrapper__main__tabs__items__item
          - item.item_images.each do |image|
            = image_tag image.image, class: 'wrapper__main__tabs__items__item__img'
            - break
          %p.wrapper__main__tabs__items__item__name
            = item.name
          %p.wrapper__main__tabs__items__item__price
            = item.price
            円 (税込)

app/views/users/_regist-credit.html.haml
.main__content
%section.chapter__container
  %h2.chapter__head クレジットカード情報入力
  = form_tag('credit_cards', method: :post, action: "create", id: 'charge-form',  name: "inputForm", class: "chapter__container__inner") do
    %li
      = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/visa.svg?238737266",width:"49px",height:"20px"
    %li
      = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?238737266",width:"34px",height:"20px"
    %li
      = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?238737266",width:"30px",height:"20px"
    %li
      = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?238737266",width:"32px",height:"20px"
    %li
      = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?238737266",width:"21px",height:"20px"
    %li
      = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?238737266",width:"32px",height:"20px"
    %li
      = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/discover.svg?238737266",width:"32px",height:"20px"
  %br
    .form__main__container
      .form__content
        %label.payment__card カード番号
        %span.require__form 必須
        = text_field_tag "number", "", class: "number input__deafult", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
        .card__list
          .card__list__picture
      .form__content.top__margin
        %label.payment__card 有効期限
        %span.require__form 必須
        .select__box.top__margin
          .select__box__half
            %select.select__default#exp_month{name: "exp_month", type: "text"}
              %option{value: ""} --
              %option{value: "1"}01
              %option{value: "2"}02
              %option{value: "3"}03
              %option{value: "4"}04
              %option{value: "5"}05
              %option{value: "6"}06
              %option{value: "7"}07
              %option{value: "8"}08
              %option{value: "9"}09
              %option{value: "10"}10
              %option{value: "11"}11
              %option{value: "12"}12
            %i
              = icon('fas', 'chevron-down')
            %span 月
          .select__box__half
            .icon
            %select.select__default#exp_year{name: "exp_year", type: "text"}
              %option{value: ""} --
              %option{value: "2019"}19
              %option{value: "2020"}20
              %option{value: "2021"}21
              %option{value: "2022"}22
              %option{value: "2023"}23
              %option{value: "2024"}24
              %option{value: "2025"}25
              %option{value: "2026"}26
              %option{value: "2027"}27
              %option{value: "2028"}28
              %option{value: "2029"}29
            %i
              = icon('fas', 'chevron-down')
            %span  年
      .form__content.top__margin
        %label セキュリティーコード
        %span.require__form 必須
        = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面4桁もしくは3桁の番号", maxlength: "4", id: "cvc"
        .single__code
          .single__code__text
          %span.form__question ? 
          %span カードの裏面の番号とは？
      #card_token
      = submit_tag "追加する", id: "token_submit", class: "top__margin"

app/views/users/credit.html.haml
.wrapper
  = render 'mypage-side'
  = render 'regist-credit'

app/views/users/edit.html.haml
.wrapper
  = render 'mypage-side'

  .form-content
    %br
    = "**** **** ****" + @default_card_information.last4
    %br
    - exp_month = @default_card_information.exp_month.to_s
    - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
    = exp_month + " / " + exp_year
    = form_tag(credit_cards_path(current_user.id), method: :delete, id: 'charge-form',  name: "inputForm") do
      %input{ type: "hidden", name: "card_id", value: "" }
      %button.delete-btn 削除する

app/views/users/logout.html.haml
.wrapper
  = render 'mypage-side'
  = render 'logout'

app/views/users/show.html.haml
.wrapper
  = render 'mypage-side'
  = render 'mypage-top'