config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
 :registrations => 'users/registrations',
 :sessions => 'users/sessions'
}
  root to: 'items#index'
  resources :items, only: [:new, :create, :show, :edit, :update, :destroy, :buy] do
    resources :buyers, only: [:index] do
      collection do
        get 'done', to: 'buyers#done'
        post 'pay', to: 'buyers#pay'
      end
    end
    resources :item_images, only: [:create, :destroy]
    member do
      get 'buy'
    end
    collection do
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
    end
  end
  resources :users, only: [:show, :edit, :update, :logout] do
    resources :profiles, only: [:new, :create] do
      collection do
        get 'show', to: 'profiles#show'
      end
    end
    resources :delivery_destinations, only: [:new, :create] do
      collection do
        get 'edit', to: 'delivery_destinations#edit'
        patch 'update', to: 'delivery_destinations#update'
      end
    end
    member do
      get 'logout'
      get 'credit'
    end
  end
  resources :credit_cards, only: [:new, :show, :destroy] do
    collection do
      post 'pay', to: 'credit_cards#pay'
    end
  end

  resources :categories, only: [:index, :show]
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :item_images, dependent: :destroy
  accepts_nested_attributes_for :item_images, allow_destroy: true
  validates_associated :item_images
  validates :item_images, presence: true
  validates :name, presence: true, length: { maximum: 40 }
  validates :description, presence: true
  validates :category_id, presence: true
  validates :condition, presence: true
  validates :postage_payer, presence: true
  validates :shipping_from, presence: true
  validates :necessary_days, presence: true
  validates :price, presence: true

  has_many :comments, dependent: :destroy
  belongs_to :category
  belongs_to :brand, optional: true
  belongs_to :seller, class_name: 'User'
  belongs_to :buyer, class_name: 'User', optional: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy, :buy]

  def index
    @items = Item.all.order("created_at DESC").limit(3)
  end

  
  def new
    @item = Item.new
    @item.item_images.new
    @category_parent_array = [["---", ""]]
    @category_parent_array = Category.where(ancestry: nil).pluck(:name, :id)
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      @category_parent_array = [["---", ""]]
      @category_parent_array = Category.where(ancestry: nil).pluck(:name, :id)
      render :new
    end
  end

  def show
    @category = Category.find(@item.category_id)
    @parentcategory = @category.parent
    @grandparentcategory = @parentcategory.parent
  end

  def edit
    @item.item_images.find_by(item_id: params[:id])
    @category_parent_array = Category.where(ancestry: nil).pluck(:name, :id)

    @category_grandparent_id = Category.find(@item.category_id).parent.parent_id
    @category_children = Category.find(@category_grandparent_id).children.pluck(:name, :id)

    @category_parent_id = Category.find(@item.category_id).parent_id
    @category_grandchildren = Category.find(@category_parent_id).children.pluck(:name, :id)
  end

  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    item = Item.find(params[:id])
    if item.destroy
      redirect_to root_path
    else
      redirect_to edit_item_path
    end
  end

  def buy
    @seller_user = User.find(@item.seller_id)
  end

  def category_children
    @category_children = Category.find(params[:parent_id]).children
  end

  def category_grandchildren
    @category_grandchildren = Category.find(params[:child_id]).children
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :description, :category_id, :brand_id, :condition, :postage_payer, :shipping_from, :necessary_days, :price, item_images_attributes: [:image, :_destroy, :id]).merge(seller_id: current_user.id)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
.exhibition-container
  .exhibition-container_registration-form
    = form_for @item do |f|
      .exhibition-container_registration-form_addphotos
        = label :photos, '出品画像', class: 'labelname'
        %span.esessential-icon 必須
        %br
        #image-box
          #previews
            - if @item.persisted?
              - @item.item_images.each_with_index do |image, i|
                = image_tag image.image.url, data:{index: i}, width: '100px', height: '100px'
          = f.fields_for :item_images do |i|
            .js-file-group{ data: {index: i.index} }
              = i.file_field :image, class: 'js-file'
              %br
              %span.js-remove 削除
            - if @item.persisted?
              = i.check_box :_destroy, data:{index: i.index}, class: 'hidden-destroy'
          - if @item.persisted?
            .js-file-group{ data: {index: @item.item_images.count}}
              = file_field_tag :image, name: "item[item_images_attributes][#{@item.item_images.count}][image]", class: 'js-file', id: "item_item_images_attributes_#{@item.item_images.count}_image"
              .js-remove 削除
        -# .addphotos
      .exhibition-container_registration-form_item_name 
        = label :item_name, '商品名', class: 'labelname'
        %span.esessential-icon 必須
        %br
        = f.text_field :name, class: 'item_name', placeholder: '40文字まで'
      .exhibition-container_registration-form_item_description
        = label :item_description, '商品説明', class: 'labelname'
        %span.esessential-icon 必須
        %br
        = f.text_area :description, class: 'item_description', placeholder: '商品の説明(色、素材、重さ、定価、注意点など)'
      %h3 商品の詳細
      .exhibition-container_registration-form_category
        = label :category, 'カテゴリー', class: 'labelname'
        %span.esessential-icon 必須
        %br
        = f.select :category_id, @category_parent_array, {selected: @category_grandparent_id, include_blank: '---'}, {class: "category", id: "parent_category"}
        - if @item.persisted?
          = f.select :category_id, @category_children, {selected: @category_parent_id, include_blank: '---'} ,{class: "category", id: "children_category"}
          = f.select :category_id, @category_grandchildren, {selected: @item.category_id, include_blank: '---'}, {class: "category", id: "grandchildren_category"}

      .exhibition-container_registration-form_brand_name
        = label :brand_name, 'ブランド', class: 'labelname'
        %span.optional-icon 任意
        %br
        %input{class: 'brand_name', placeholder: 'シャネル'}
      .exhibition-container_registration-form_item_condition
        = label :category, '商品の状態', class: 'labelname'
        %span.esessential-icon 必須
        %br
        = f.select :condition, [['新品 未使用'],['未使用に近い'],['目立った傷や汚れなし']], {include_blank: '---'}, {class: "item_condition"}
      %h3 配送について
      .exhibition-container_registration-form_charge
        = label :charge, '発送料の負担額', class: 'labelname'
        %span.esessential-icon 必須
        %br
        = f.select :postage_payer, [['送料込み'],['着払い']], {include_blank: '---'}, {class: "charge"}
      .exhibition-container_registration-form_area
        = label :area, '発送元の地域', class: 'labelname'
        %span.esessential-icon 必須
        %br
        = f.select :shipping_from, ["北海道","青森県","岩手県","宮城県","秋田県","山形県","福島県","茨城県","栃木県","群馬県","埼玉県","千葉県","東京都","神奈川県","新潟県","富山県","石川県","福井県","山梨県","長野県","岐阜県","静岡県","愛知県","三重県","滋賀県","京都府","大阪府","兵庫県","奈良県","和歌山県","鳥取県","島根県","岡山県","広島県","山口県","徳島県","香川県","愛媛県","高知県","福岡県","佐賀県","長崎県","熊本県","大分県","宮崎県","鹿児島県","沖縄県"], {include_blank: '---'}, {class: "area"}
      .exhibition-container_registration-form_day
        = label :day, '発送までの日数', class: 'labelname'
        %span.esessential-icon 必須
        %br
        = f.select :necessary_days, [['1〜2日で発送'],['3〜4日で発送'],['5〜7日で発送']], {include_blank: '---'}, {class: "day"}
      %h6 価格(¥300~9,999,999)
      .exhibition-container_registration-form_price
        = label :price, '販売価格', class: 'labelname'
        %span.esessential-icon 必須
        %br
        = f.text_field :price, class: 'price', placeholder: '0'
      = f.submit value: "出品する", class: "exhibition"

app/views/items/buy.html.haml
-# 購入確認ページです
.buying
  .buying_contents1
    購入内容の確認
  .buying_contents2
    .buying_contents2_item
      =image_tag "#{@item.item_images[0].image}", size: "100x100"
      .buying_contents2_item_image
        .buying_contents2_item_image_name
          = @item.name
        .buying_contents2_item_image_total
          = @item.price
          円(税込)
  .buying_front
    .buying_front_contents3
      .buying_front_contents3_buy
        .buying_front_contents3_buy_label
          支払い金額
        .buying_front_contents3_buy_price
          ¥
          = @item.price
      .buying_front_contents3_how
        支払い方法
      .buying_front_contents3_register
        - if current_user.credit_card
          クレジットカード登録済み
        - else
          = link_to "#" do
            = icon('fas fa-plus-circle', class: "register-icon")
            登録してください
      .buying_front_contents3_send
        .buying_front_contents3_send_left
          配送先
        .buying_front_contents3_send_change
          = link_to "＃" do
            変更する
      .buying_front_contents3_address
        = current_user.delivery_destination.postal_code
        %br
        = current_user.delivery_destination.prefecture
        = current_user.delivery_destination.city
        = current_user.delivery_destination.house_number
        = current_user.delivery_destination.building_name
      .buying_front_contents3_text
        郵便局/コンビニ受取をご希望の方は、購入後、
        %span 取引画面
        から受取場所変更をすることが可能です。出品者が発送作業を開始した後には受取場所変更ができませんので、早めに受取場所の変更を行ってください。

        = form_tag(action: :pay, method: :post) do
          %button.buy-button{type:"submit"} 購入する

 

app/views/items/edit.html.haml
= render partial: 'form'

app/views/items/index.html.haml
-# 商品一覧ページ(トップページ)のviewファイルです

.main
  .main-pic
    .main-pic__content
      .main-pic__content__title
        人生を変えるフリマアプリ

      .main-pic__content__message
        FURIMAはだれでもかんたんに出品・購入できる
        %br
        フリマアプリです
      .main-pic__content__btn
        .main-pic__content__btn__ap
          =link_to image_tag("app-store.png", alt: "appstore"), "https://www.apple.com/jp/ios/app-store/", class: "ap-btn"
        .main-pic__content__btn__gp
          =link_to image_tag("google-play.png", alt: "googleplay"), "https://play.google.com/store", class: "gp-btn"

.top-3
  .top-3__title
    FURIMAが選ばれる３つの理由
    .top-3__title__line
  .top-3__list
    .top-3__list__item
      .top-3__list__item__pic
        =image_tag("top2.jpg")
        .top-3__list__item__pic__num
          1
      .top-3__list__item__text1
        <span>3分</span> ですぐに出品
      .top-3__list__item__text2
        スマホで入力するだけで簡単に出品で
        %br
        きる！
    
    .top-3__list__item
      .top-3__list__item__pic
        =image_tag("top3.jpg")
        .top-3__list__item__pic__num
          2
      .top-3__list__item__text1
        <span>シンプル</span> で使いやすい
      .top-3__list__item__text2
        めんどくさい入力は必要なく、検索も
        %br 
        購入もスムーズ！

    .top-3__list__item
      .top-3__list__item__pic
        =image_tag("top4.jpg")
        .top-3__list__item__pic__num
          3
      .top-3__list__item__text1
        <span>手数料</span> 業界最安
      .top-3__list__item__text3
        最大３％でお得に出品＆購入！

.middle-pic
  .middle-pic__text
    .middle-pic__text__title
      会員数日本一位
    .middle-pic__text__message
      FURIMAは、フリマアプリで最も人気。
      %br
      出品・購入回数も業界最多です！
      %br
      ほしかったあの商品に出会えるかもしれません。
    .middle-pic__text__btn
      .middle-pic__text__btn__ap
        =link_to image_tag("app-store.png", alt: "appstore"), "https://www.apple.com/jp/ios/app-store/", class: "ap-btn"
      .middle-pic__text__btn__gp
        =link_to image_tag("google-play.png", alt: "googleplay"), "https://play.google.com/store", class: "gp-btn"

.top-images
  .top-images__title
    FURIMAの特徴
    .top-images__title__line
  
  .top-images__item
    .top-images__item__image
      .top-images__item__image__pic
        =image_tag("icon-01.png")
      .top-images__item__image__title
        簡単に売り買いできる
      .top-images__item__image__text
        スマホひとつで、いつでもどこでも簡単
        %br
        に出品・購入が可能！

    .top-images__item__image
      .top-images__item__image__pic
        =image_tag("icon-03.png")
      .top-images__item__image__title
        売上金は即日振込みに対応
      .top-images__item__image__text
        午前９時までに振込を以来いただけれ
        %br
        ば、翌日に指定の口座に入金いたします！

    .top-images__item__image
      .top-images__item__image__pic
        =image_tag("icon-04.png")
      .top-images__item__image__title
        様々な支払いに対応
      .top-images__item__image__text
        お支払いは、クレジットカードだけでな
        %br
        く、ポイントや売上金など多彩な方法が
        %br
        あります。


.picup
  .picup__title
    ピックアップカテゴリー
  .picup__box
    .picup__box__title
      新規投稿商品
    .picup__box__list
      - @items.each do |item|
        =link_to item_path(item.id) do
          .picup__box__list__item
            .picup__box__list__item__pic
              - unless item.buyer_id
                - item.item_images.each do |image|
                  = image_tag image.image
                  - break
              - else
                - item.item_images.each do |image|
                  = image_tag image.image
                  - break
                .picup__box__list__item__pic__sold
                  .picup__box__list__item__pic__sold__inner
                    SOLD
            .picup__box__list__item__name
              = item.name
            .picup__box__list__item__price
              = item.price
              円 (税込)

app/views/items/new.html.haml
= render partial: 'form'

app/views/items/show.html.haml
.details
  .details_contents
    .details_contents_title
      .details_contents_title_name
        = @item.name
    .details_contents_image
      .details_contents_image_image1
        - @item.item_images.each do |image|
          = image_tag image.image, size: "560x346"
          -break
      .details_contents_image_images
        .details_contents_image_images_fail
          - @item.item_images.each do |image|
            = image_tag image.image, size:"140x87"
            
    .details_contents_price
      = @item.price
      円
    .details_contents_tax
      (税込) 送料込み

    - if user_signed_in? && current_user.id != @item.seller_id && @item.buyer_id.blank?
      .details_contents_purchase_btn
        = link_to item_buyers_path(params[:id]) do
          購入画面に進む

    .details_contents_text
      = simple_format @item.description
    %table
      %tbody
        %tr
          %th 出品者
          %td 
            = @item.seller.nickname
            
        %tr
          %th カテゴリー
          %td
            %span -
            = link_to @item.category.name, class:"category-n" do
              = @grandparentcategory.name
            %br
            %span -
            = link_to @item.category.name, class:"category-n" do
              = @parentcategory.name
            %br
            %span -
            = link_to @item.category.name, class:"category-n" do
              = @category.name

        -# %tr
        -#   %th ブランド
        -#   %td 
        -#     = link_to "※ブランドのリンクが入ります※"

        %tr 
          %th 商品の状態
          %td 
            = @item.condition
        %tr
          %th 配送料の負担
          %td 
            = @item.postage_payer
        %tr
          %th 発送元の地域
          %td 
            = @item.shipping_from
        %tr
          %th 発送日の目安
          %td 
            = @item.necessary_days

    .details_contents_option
      .details_contents_option_like
        = link_to "#" do
          = icon('fas fa-star', class: "like-icon")
          お気に入り
      .details_contents_option_optional
        = link_to "#" do
          = icon('fab fa-font-awesome-flag', class: "flag-icon")
          不適切な商品の通報
  
    - if user_signed_in? && current_user.id == @item.seller_id && @item.buyer_id.blank?
      .details_edit
        .details_edit_item
          =link_to edit_item_path(params[:id]) do
            商品の編集
        .details_edit_delete
          =link_to item_path(params[:id]), method: :delete do
            この商品を削除する
    - elsif @item.buyer_id.present?
      .details_edit
        .details_edit_sold
          %p SOLD OUT

  .details_comment
    .details_comment_box
      %textarea  
    .details_comment_info
      相手のことを考え丁寧なコメントを心がけましょう。
      %br
      不快な言葉遣いなどは利用制限や退会処分となることがあります。
    .details_comment_btn
      %button{type: "submit", class: 'submit-btn'}
        コメントする

  .details_links
    .details_links_back
      = link_to "#" do
        = icon('fas fa-chevron-left', class: "back-icon")
        前の商品
    .details_links_next
      = link_to "#" do
        後ろの商品
        = icon('fas fa-chevron-right', class: "next-icon")
  .details_more
    = link_to "#" , class:"brandlink" do
      ＞
      = @item.category.name
      をもっと見る