config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
 :registrations => 'users/registrations',
 :sessions => 'users/sessions'
}
  root to: 'items#index'
  resources :items, only: [:new, :create, :show, :edit, :update, :destroy, :buy] do
    resources :buyers, only: [:index] do
      collection do
        get 'done', to: 'buyers#done'
        post 'pay', to: 'buyers#pay'
      end
    end
    resources :item_images, only: [:create, :destroy]
    member do
      get 'buy'
    end
    collection do
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
    end
  end
  resources :users, only: [:show, :edit, :update, :logout] do
    resources :profiles, only: [:new, :create] do
      collection do
        get 'show', to: 'profiles#show'
      end
    end
    resources :delivery_destinations, only: [:new, :create] do
      collection do
        get 'edit', to: 'delivery_destinations#edit'
        patch 'update', to: 'delivery_destinations#update'
      end
    end
    member do
      get 'logout'
      get 'credit'
    end
  end
  resources :credit_cards, only: [:new, :show, :destroy] do
    collection do
      post 'pay', to: 'credit_cards#pay'
    end
  end

  resources :categories, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user

  validates :costomer_id, :card_id, presence: true
end

app/models/delivery_destination.rb
class DeliveryDestination < ApplicationRecord
  belongs_to :user, optional: true
 
    validates :destination_family_name, presence: true
    validates :destination_first_name, presence: true
    validates :destination_family_name_kana, presence: true
    validates :destination_first_name_kana, presence: true
    validates :postal_code, presence: true
    validates :prefecture, presence: true
    validates :city, presence: true
    validates :house_number, presence: true

  # with_options presence: true do
  #   validates :destination_family_name
  #   validates :destination_first_name
  #   validates :destination_family_name_kana
  #   validates :destination_first_name_kana
  #   # validates :postal_code, format: {with: /\A\d{3}[-]\d{4}\z/}
  #   validates :prefecture
  #   validates :city
  #   validates :house_number
  # end

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :item_images, dependent: :destroy
  accepts_nested_attributes_for :item_images, allow_destroy: true
  validates_associated :item_images
  validates :item_images, presence: true
  validates :name, presence: true, length: { maximum: 40 }
  validates :description, presence: true
  validates :category_id, presence: true
  validates :condition, presence: true
  validates :postage_payer, presence: true
  validates :shipping_from, presence: true
  validates :necessary_days, presence: true
  validates :price, presence: true

  has_many :comments, dependent: :destroy
  belongs_to :category
  belongs_to :brand, optional: true
  belongs_to :seller, class_name: 'User'
  belongs_to :buyer, class_name: 'User', optional: true
end

app/models/item_image.rb
class ItemImage < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :item, optional: true
  validates :image, presence: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user, optional: true
  
  
  
    validates :first_name, presence: true
    validates :family_name, presence: true
    validates :first_name_kana, presence: true
    validates :family_name_kana, presence: true
    validates :birth_day, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile, dependent: :destroy
  accepts_nested_attributes_for :profile
  has_one :credit_card, dependent: :destroy
  has_one :delivery_destination, dependent: :destroy
  accepts_nested_attributes_for :delivery_destination
  has_many :comments, dependent: :destroy
  has_many :buyer_items, foreign_key: "buyer_id", class_name: 'Items'
  has_many :seller_items, foreign_key: "seller_id", class_name: 'Items'
  

    validates :nickname, presence: true
    validates :email, presence: true
    validates :email, uniqueness: true
    validates :password, length: {minimum: 7}


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy, :buy]

  def index
    @items = Item.all.order("created_at DESC").limit(3)
  end

  
  def new
    @item = Item.new
    @item.item_images.new
    @category_parent_array = [["---", ""]]
    @category_parent_array = Category.where(ancestry: nil).pluck(:name, :id)
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      @category_parent_array = [["---", ""]]
      @category_parent_array = Category.where(ancestry: nil).pluck(:name, :id)
      render :new
    end
  end

  def show
    @category = Category.find(@item.category_id)
    @parentcategory = @category.parent
    @grandparentcategory = @parentcategory.parent
  end

  def edit
    @item.item_images.find_by(item_id: params[:id])
    @category_parent_array = Category.where(ancestry: nil).pluck(:name, :id)

    @category_grandparent_id = Category.find(@item.category_id).parent.parent_id
    @category_children = Category.find(@category_grandparent_id).children.pluck(:name, :id)

    @category_parent_id = Category.find(@item.category_id).parent_id
    @category_grandchildren = Category.find(@category_parent_id).children.pluck(:name, :id)
  end

  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    item = Item.find(params[:id])
    if item.destroy
      redirect_to root_path
    else
      redirect_to edit_item_path
    end
  end

  def buy
    @seller_user = User.find(@item.seller_id)
  end

  def category_children
    @category_children = Category.find(params[:parent_id]).children
  end

  def category_grandchildren
    @category_grandchildren = Category.find(params[:child_id]).children
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :description, :category_id, :brand_id, :condition, :postage_payer, :shipping_from, :necessary_days, :price, item_images_attributes: [:image, :_destroy, :id]).merge(seller_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
    # ↓の seller_id:, buyer_id: は仮に"1"としている 実際はログインしているユーザーのidを入れたい
    @sell_items = Item.where(seller_id: current_user.id).order("created_at DESC").limit(3)
    @buyed_items = Item.where(buyer_id: current_user.id).order("created_at DESC").limit(3)
  end

  def edit
    card = CreditCard.find_by(user_id: current_user.id)
    if card.blank?
      redirect_to new_card_path 
    else
      Payjp.api_key = Rails.application.secrets[:PAYJP_PRIVATE_KEY]
      customer = Payjp::Customer.retrieve(card.costomer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  def update
  end

  def logout
  end

  def credit
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/item_images_helper.rb
module ItemImagesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_fooder.html.haml
.appBanner
  .appBanner__inner
    .appBanner__inner__title
      だれでもかんたん、人生を変えるフリマアプリ
    .appBanner__inner__text
      今すぐ無料ダウンロード!
    .appBanner__inner__icon
      =link_to image_tag("app-store.png", alt: "appstore"), "https://www.apple.com/jp/ios/app-store/", class: "ap-btn"
      =link_to image_tag("google-play.png", alt: "googleplay"), "https://play.google.com/store", class: "gp-btn"

.fooder
  .fooder__contents
    .fooder__contents__content
      %ul.fooder__contents__content__header
        FURIMAについて
      %li.fooder__contents__content__list
        会社概要(運営会社)
      %li.fooder__contents__content__list
        プライバシーポリシー
      %li.fooder__contents__content__list
        FURIMA利用規約
      %li.fooder__contents__content__list
        ポイントに関する特約
    .fooder__contents__content
      %ul.fooder__contents__content__header
        FURIMAを見る
      %li.fooder__contents__content__list
        カテゴリー一覧
      %li.fooder__contents__content__list
        ブランド一覧
    .fooder__contents__content
      %ul.fooder__contents__content__header
        ヘルプ&ガイド
      %li.fooder__contents__content__list
        FURIMAガイド
      %li.fooder__contents__content__list
        FURIMAロゴ利用ガイドライン
      %li.fooder__contents__content__list
        お知らせ
  .fooder__logo
    =link_to image_tag("logo2.png", alt: "logo"), root_path, class: "image"
    .fooder__logo__name
      © FURIMA
- if user_signed_in?
  .purchasebtn
    .purchasebtn__text
      出品する
    .purchasebtn__icon
      =link_to image_tag("camera.png", alt: "出品アイコン"), new_item_path, class: "sp-btn"

app/views/layouts/_footer.html.haml
.appBanner
  .appBanner__inner
    .appBanner__inner__title
      だれでもかんたん、人生を変えるフリマアプリ
    .appBanner__inner__text
      今すぐ無料ダウンロード!
    .appBanner__inner__icon
      =link_to image_tag("app-store.png", alt: "appstore"), "https://www.apple.com/jp/ios/app-store/", class: "ap-btn"
      =link_to image_tag("google-play.png", alt: "googleplay"), "https://play.google.com/store", class: "gp-btn"

.footer
  .footer__contents
    .footer__contents__content
      %ul.footer__contents__content__header
        FURIMAについて
      %li.footer__contents__content__list
        会社概要(運営会社)
      %li.footer__contents__content__list
        プライバシーポリシー
      %li.footer__contents__content__list
        FURIMA利用規約
      %li.footer__contents__content__list
        ポイントに関する特約
    .footer__contents__content
      %ul.footer__contents__content__header
        FURIMAを見る
      %li.footer__contents__content__list
        カテゴリー一覧
      %li.footer__contents__content__list
        ブランド一覧
    .footer__contents__content
      %ul.footer__contents__content__header
        ヘルプ&ガイド
      %li.footer__contents__content__list
        FURIMAガイド
      %li.footer__contents__content__list
        FURIMAロゴ利用ガイドライン
      %li.footer__contents__content__list
        お知らせ
  .footer__logo
    =link_to image_tag("logo2.png", alt: "logo"), root_path, class: "image"
    .footer__logo__name
      © FURIMA
- if user_signed_in?
  .purchasebtn
    .purchasebtn__text
      出品する
    .purchasebtn__icon
      =link_to image_tag("camera.png", alt: "出品アイコン"), new_item_path, class: "sp-btn"

app/views/layouts/_header.html.haml
.header
  .header-bar
    .header-bar__main-header
      .header-bar__main-header__icon
        =link_to image_tag("logo.png", alt: "furimaアイコン"), root_path, class: "image"
      .header-bar__main-header__searchbox
        .header-bar__main-header__searchbox__text
          %input{placeholder:  "キーワードから探す"}
        .header-bar__main-header__searchbox__btn
          =link_to image_tag("icon-search1.png", alt: "サーチアイコン"), "/", class: "s-btn"
        
    .header-bar__navbar
      .header-bar__navbar__menu
        .header-bar__navbar__menu__category
          = link_to "カテゴリー", categories_path 
          %ul.index-categories
            - @parents.each do |parent|
              = link_to category_path(parent.id) do
                %li.category-name
                  = parent.name
              -# %ul.index-sub-categories
              -#   - parent.children.each do |child|
              -#     = link_to "#" do
              -#       %li.sub-category-name
              -#         = child.name
        .header-bar__navbar__menu__brand
          =link_to "ブランド", '#'
      .header-bar__navbar__user
        - if user_signed_in?
          .header-bar__navbar__user__login
            =link_to "ログアウト", destroy_user_session_path, method: :delete
          .header-bar__navbar__user__new
            =link_to "マイページ", user_path(current_user.id)
        - else
          .header-bar__navbar__user__login
            =link_to "ログイン", new_user_session_path
          .header-bar__navbar__user__new
            =link_to "新規会員登録", new_user_registration_path

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FreemarketSample72a
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
  %body
    =render "layouts/header"
    -# = render 'layouts/notifications'

    
  .breadcrumbs
    = breadcrumbs pretext: "",separator: " &rsaquo; ", class: "breadcrumbs-list"
 

    = yield


    =render "layouts/footer"